version: "3.5"

services:
  app:
    environment:
      - SENTRY_ENV=development
      - SENTRY_SAMPLE_RATE=0
#      - DATASOURCE_HOST_PORT=postgres:5432
#      - DATASOURCE_DBNAME=crime_means_assessment
#      - DATASOURCE_USERNAME=postgres
#      - DATASOURCE_PASSWORD=postgres
      - LOG_LEVEL=DEBUG
    env_file:
      - app.env
    ports:
      - "8080:8080"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080 -jar app.jar

#  postgres:
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=crime_means_assessment