spring:
  application:
    name: LAA Crime Court Message Processor Microservice
  profiles:
    active: dev
  cloud:
    aws:
      region:
        static: eu-west-2

  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  #do not auto create db schema, use .sql scripts
  jpa:
    hibernate:
      ddl-auto: none

# used by actuator info endpoint
info:
  app:
    name: LAA Crime Court Message Processor Microservice application
    description: Crime Court Message Processor Microservice application that provides a REST API.
    version: 1.0.0

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health

  # show detailed health status
  endpoint:
    health:
      show-details: always
